markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
        span:
            line_number: false
        block:
            line_number: true
            start_line: 1
gems: []
